### PR TITLE
V4 Beta 10

### PR DESCRIPTION
**Pull request by kreso123**
dxdds

### CODE REVIEW

**Comment by mike1072** [comment]
It looks like your files and folders were copied into the repo folder directly, instead of into the item_rev folder instead the repo.

**Comment by kreso123** [comment]
what can I say? If I wanted to repeat what I've done I wouldn't be able to. :)

**Comment by mike1072** [comment]
You can move the files and folders into the item_rev folder and create a new commit, then sync up and the pull request will automatically be updated.

**Comment by kreso123** [comment]
Gimme a sec, I'll see if I can upload again.

**Comment by kreso123** [comment]
I did upload again, then "merged". ??

**Comment by mike1072** [comment]
Hmm, you made some changes to your files, but they are still in the same spot (e.g. ItemRevisions/languages/english/item_descriptions.tra) when they need to be moved into the item_rev folder (e.g. ItemRevisions/item_rev/languages/english/item_descriptions.tra).

**Comment by mike1072** [comment]
Hah, now they're in a subfolder called ItemRevisions.  Okay, I can try to fix things up from here.

**Comment by kreso123** [comment]
...............signing off. I've had it. :)

**Comment by mike1072** [comment]
I've rebased your changes on top of the pending ones from my repo, so I'll close this PR.

**Pull request closed without merging**
