### PR TITLE
Revised launchers ammo

### PR DESCRIPTION
**Pull request by mercurier**
Assimilation of Dee's mod for bestowing launcher enchantment to ammo in EE games, requested by Demi and approved by Dee
https://forums.beamdog.com/discussion/58374/enchant-the-missile-launchers-ranged-weapon-tweak

Magical ammo no longer have thac0 and damage bonus except for those from secondary effects as all launchers in IR already includes them -- not a perfect solution yet consider that when you get them you usually already have higher enchantment launchers
Magical ammo enchantment level all set to 1 except for plain +2/+3/+4 ones

### CODE REVIEW

**Comment by mike1072** [comment]
Thanks, I'll take a look.

**Comment by mike1072** [comment]
I checked out that thread and the commits.  Thanks for putting it all together.  I have a couple of comments.

1) Conceptually, what do the plain +2/+3/+4 ammos provide if their THAC0 and damage bonuses are removed?  There aren't too many creatures that require enchanted ammo to hit to justify hoarding them... and once you get an enchanted launcher, that bonus goes away as well.  I don't know if this is what Demi intended to do.  We probably don't want doubly stacking damage/THAC0, but they need to have some benefit over plain arrows.

2) Demi probably intended these changes to go into the Weapon Changes component.

3) We should expand the lists of plain enchanted ammo to catch plain ammos added by mods.

**Comment by mercurier** [comment]
1. Per PnP launcher and ammo enchantment (and the associated damage/thac0 bonus) should not stack, but the higher one takes precedence. Current EE engine provides limited support for this rule for the enchantment part (determining what the weapon can hit), but not for the damage/thac0 part. IMHO stripping off damage/thac0 from ammo could be a close approximation: players can still hit dragons/liches with +0/+1/+2 launcher plus +3 ammo, but will lost a little bit of damage/thac0, which I guess is not too big deal. A good application is using Strong Arm (+2) and +3 ammo to quickly takeout dragons.

2. Please feel free to move this component around :)

3. The code block I submitted patches all ammo that have enchantment level >0, i.e. those get blocked by PFMW. If any mod introduces non-magical ammo with magic-like ability, I guess either their abilities come from physics/alchemy/whatever sources, or they were flagged as non-magical by mistake.

**Comment by mercurier** [comment]
Additional note here:
In my personal mod I changed Strong Arm to a non-magical short composite bow crafted by its original owner-- an ogre hunter. In player's hand it functions as a composite longbow requiring 19 str (+8 dmg) -- good at wiping off mobs yet requires rare ammo for serious boss fights. 

This  is a good example that an early game equipment gets extended utility during late game. Some players use weimer's item upgrade mod so that their beloved Celestial Fury gets extended utility. I envision this tweak will open the road for more flexible and innovative item designs.

**Comment by mike1072** [comment]
1. Yeah, but the effect of this change is that the majority of the time, +1/+2/+3 ammo would function no differently from unenchanted ammo.  Once you got a +2 weapon, +2 ammo would be worthless.  I think it might be good to move this discussion to the forums.

2. Can do.  I'll leave the pull request up for now and push additional commits to it later before merging.

3. What I mean is there might be some mods that introduce +4 or +5 ammos.

**Comment by mercurier** [comment]
Thoroughly implemented in my mod:
https://github.com/mercurier/mcr_salt_and_pepper

**Pull request closed without merging**
